version: '3'

services:
  db: &db
    image: frodenas/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
      POSTGRES_DBNAME: postgres
      POSTGRES_EXTENSIONS: uuid-ossp
    container_name: db